name: .NET Core Desktop

on:
  push:
    branches: [ "develop", "nightly" ]

env:
  AppUuid: "FalconNL93.WSLToolbox"
  AppName: "WSL Toolbox"
  AppDescription: "WSL Toolbox allows you to manage your WSL Distributions through an easy to use interface."
  AppExecutable: "toolbox.exe"
  AppVersion: '0.6.${{ github.run_number }}'
  AppUrl: "https://github.com/FalconNL93/wsltoolbox"
  AppOwner: "FalconNL93"
  SetupOutputFile: "wsltoolbox-setup"

jobs:
    
  build:
    strategy:
      matrix:
        configuration: [ Release ]
        platform: [ x64 ]
    runs-on: windows-latest
    env:
      Platform: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Publish
        run: |
          dotnet publish "WslToolbox.UI\WslToolbox.UI.csproj" `
          -p:PublishProfile="${{ env.Platform }}" `
          -p:Version="${{ env.AppVersion }}" `
          -p:FileVersion="${{ env.AppVersion }}" `
          -p:AssemblyVersion="${{ env.AppVersion }}" `
          -p:PublishTrimmed=True `
          -p:TrimMode=CopyUsed `
          --self-contained `
          -r win-${{ env.Platform }} `
          --nologo `
          -o "${{ github.workspace }}\app\release\${{ env.Platform }}"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: release
          path: ${{ github.workspace }}\app\release\${{ env.Platform }}
          retention-days: 1
  
  setup:
    env:
      Platform: "x64"
    runs-on: windows-2022
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Download build data
        uses: actions/download-artifact@v3
        with:
          name: release
          path: ${{ github.workspace }}\app

      - name: Setup
        run: |
          .\WslToolbox.Setup\build.ps1 `
          -AppDirectory "${{ github.workspace }}\app" `
          -AppUuid "${{ env.AppUuid }}" `
          -AppName "${{ env.AppName }}" `
          -AppDescription "${{ env.AppDescription }}" `
          -AppExecutable "${{ env.AppExecutable }}" `
          -AppVersion "${{ env.AppVersion }}" `
          -AppUrl "${{ env.AppUrl }}" `
          -AppOwner "${{ env.AppOwner }}" `
          -SetupOutputFile "${{ env.SetupOutputFile }}-${{ env.Platform }}-setup"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: WslToolbox.Setup\bin\${{ env.SetupOutputFile }}-${{ env.Platform }}-setup.exe
          retention-days: 1

  purge:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
